const sonidoBoton = new Audio('./SONIDOS/coger_algo_bueno.mp3');
const sonidoExplosion = new Audio('./SONIDOS/explosion.wav');
const sonidoGameover = new Audio('./SONIDOS/GAMEOVER.wav');
const sonidointerferencia = new Audio('./SONIDOS/interferencia.wav');
const sonidointerferencia2 = new Audio('./SONIDOS/interferencia2.wav');
const sonidoIntro = new Audio('./SONIDOS/intro.wav');
const sonidoMusicaGame = new Audio('./SONIDOS/musica_game.wav');
const sonidoshot1 = new Audio('./SONIDOS/shot_1.wav');
const sonidoshot2 = new Audio('./SONIDOS/shot_2.wav');
const sonidoshot3 = new Audio('./SONIDOS/shot_3.wav');
const sonidoEscudoLaser = new Audio('./SONIDOS/escudo_laser.wav');
const sonidoLevelUp = new Audio("./SONIDOS/lvl_up.wav")
const sonidoParasConEscudo = new Audio ("./SONIDOS/paras_con_escudo.mp3")
const sonidoShotBoss = new Audio ("./SONIDOS/shotBoss.wav")
const sonidoVictoria = new Audio ("./SONIDOS/victoria.mp3")
const golpeoEnemigo = new Audio ("./SONIDOS/golpeoEnemigo.wav")